Add bottom navigation layout to home controller
Flipper-Zero/Flipper-Android-App pull request #33
Opened 2020-09-04 11:53 UTC by rougsig

2020-09-09 08:12 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Flipper-Zero/Flipper-Android-App?pullRequest=33) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Flipper-Zero/Flipper-Android-App?pullRequest=33) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Flipper-Zero/Flipper-Android-App?pullRequest=33) it.</sub>

2020-09-09 08:40 UTC, IlyaGulya requested changes

2020-09-09 08:40 UTC, IlyaGulya commented on app/src/main/java/com/flipper/app/home/ui/HomeView.kt
>  @StateStrategyType(SingleStateStrategy::class)
Moxy supports state strategy aliases.
For instance, istead of ` @StateStrategyType(SingleStateStrategy::class)` you can write `@SingleState`

2020-09-09 08:40 UTC, IlyaGulya commented on app/src/main/java/com/flipper/app/home/ui/HomeView.kt
>  @StateStrategyType(SingleStateStrategy::class)
Also, I'd suggest using `@AddToEndSingle` as default strategy for consistency across the project.

2020-09-09 08:40 UTC, IlyaGulya commented on app/src/main/java/com/flipper/app/home/ui/data/HomeTab.kt
> +        }
How about rewriting this way?
In this case we will not need to maintain `createFromMenuItemId` method.
```
fun createFromMenuItemId(itemId: Int): HomeTab? {
    return values().firstOrNull { tab -> tab.menuItemId == itemId }.also { tab -> 
        if (tab == null) {
            Timber.e("unknown item id in home tabs: itemId=${itemId}")
        }
    }
}
```

2020-09-09 08:40 UTC, IlyaGulya commented on app/src/main/java/com/flipper/app/stub/StubController.kt
> +    lateinit var presenter: StubPresenter
How about using `by moxyPresenter` instead?
```
val presenter by moxyPresenter {
  StubPresenter()
}
```
To use it you should add `implements MvpDelegateHolder` to `BaseController` and add `implementation "com.github.moxy-community:moxy-ktx:$moxyVersion"` dependency

2020-09-09 08:40 UTC, IlyaGulya commented on core/src/main/java/com/flipper/core/view/BaseController.kt
> +        }
You should use `mvpDelegate.onCreate(savedViewState)` instead of checking for `isCreated` on your own.

2020-09-09 08:40 UTC, IlyaGulya commented on core/src/main/java/com/flipper/core/view/BaseController.kt
> +        mvpDelegate.onDestroy()
I think it would be better to use `!isBeingDestroyed` instead of `isStateSaved`

2020-09-09 08:47 UTC, LionZXY commented on app/src/main/java/com/flipper/app/home/ui/HomeView.kt
>  @StateStrategyType(SingleStateStrategy::class)
Or write default state in gradle file

2020-09-09 08:51 UTC, IlyaGulya commented on app/src/main/java/com/flipper/app/home/ui/HomeView.kt
>  @StateStrategyType(SingleStateStrategy::class)
I think that manually assigning state strategy to each View interface is better because it's obvious which default strategy is used. If we will assign it as `apt` argument it will be less obvious.
That's why Moxy removed default strategy in 2.x version

2020-09-09 09:33 UTC, rougsig commented on core/src/main/java/com/flipper/core/view/BaseController.kt
> +        mvpDelegate.onDestroy()
I'd prefer to keep isStateSaved, because i guess latter we will need to check if activity is finishing and for that `isBeingDestroyed` better name.

2020-09-09 09:43 UTC, rougsig commented on core/src/main/java/com/flipper/core/view/BaseController.kt
> +        }
See comment under isCreated field

2020-09-09 13:05 UTC, IlyaGulya commented on core/src/main/java/com/flipper/core/view/BaseController.kt
> +        mvpDelegate.onDestroy()
No, you don't get it :smile: 
Conductor `Controller` already does all that stuff internally and exposes is as simple flag `isBeingDestroyed` which you can already use without needance to maintain it on your own.

2020-09-09 13:48 UTC, rougsig commented on core/src/main/java/com/flipper/core/view/BaseController.kt
> +        mvpDelegate.onDestroy()
No. isBeingDestroyed is means rotation to.

2020-09-13 16:14 UTC, LionZXY commented
BottomNavigationView must fill all width

![image](https://user-images.githubusercontent.com/5871715/93023088-3ac4f380-f5f5-11ea-87d0-b16e5f647e8e.png)

2020-09-13 17:05 UTC, LionZXY approved these changes

2020-09-18 15:13 UTC, merged